version: "3"
services:
    flask:
        build: ./Flask
        ports:
          - 5000:5000
        depends_on:
          - web

    web:
        build: .
        depends_on:
            - redis
    redis:
        image: redis
